Adding roadmap points
ericadamski/atom-medium pull request #12
Opened 2017-03-02 19:04 UTC by ChrisChinchilla

Moving over a few roadmap points, if you have these already, just remove or tick that one.

2017-12-15 13:53 UTC, ericadamski requested changes
@ChrisChinchilla sorry about never looking through this! I want to do a lot of refactoring of this code and really get this package to a state that more people can maintain it so I am going to push all these PRs through. If you cannot devote the time to changes on these just let me know and I can fix them all to get them merged!

2017-12-15 13:53 UTC, ericadamski commented on README.md
> +![info-bar](https://raw.githubusercontent.com/ericadamski/atom-atom-medium/master/assets/info-bar.png)
this should be renamed to `atom-medium`

2017-12-15 13:53 UTC, ericadamski commented on README.md
> +![menu item](https://raw.githubusercontent.com/ericadamski/atom-atom-medium/master/assets/menu-item.png)
Same with this one

2017-12-15 13:53 UTC, ericadamski commented on CHANGELOG.md
> +* [Stop using reserved JavaScript keyword `package`](https://github.com/ericadamski/atom-atom-medium/pull/9)
this should be renamed to `atom-medium`

2018-01-04 14:52 UTC, ChrisChinchilla commented
To be honest @ericadamski I hit a lot of the authentication issues that Jared hit in recent issues and got a bit stuck. I will attempt to pick up the ball again if you're still keen, but for now, just go ahead with making the changes you want.

2018-01-04 15:06 UTC, ericadamski commented
@ChrisChinchilla I think I need to spend some time to re-write this package because coming back to it the logic is all over the place 😜 I think the issue #14 my bring some attention to the authentication issues as we comb through the code

2018-05-22 11:56 UTC, ericadamski commented
This PR is out-of-date but the road map items still relevant have been added.

2018-05-22 11:56 UTC, closed without merging